# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Symbols used (https://www.nerdfonts.com/cheat-sheet)
# e0b6 î‚¶, e0b4 î‚´, e0ba î‚º, e0bc î‚¼, e0b8 î‚¸, e0b0 î‚°, e691 îš‘, # f007 ï€‡, f07c ï¼, e0a0 î‚ , f017 ï€—, f00ed ó°ƒ­, e0c6 îƒ†, f075a ó°š

# Hints
# * When a string is enclosed by parenthesis, it doesn't render if all variables inside are None or empty
# * prev_bg and prev_fg are valid values for colors

# Pastel
#903284 #FFFFFF
#D65B71 #FFFFFF
#F0986F #000000
#7AB2D3 #000000
#2C597F #FFFFFF
#D0D0D0

# Blue
#3B237A #FFFFFF
#33658A #FFFFFF
#86BBD8 #000000
#ABABAB #000000
#B497FF

# Rainbow
#064A74 #FFFFFF
#7E1014 #FFFFFF
#B30020 #FFFFFF
#DD962C #000000
#FAD300 #000000
#00D000

# Optional first section
#[ îš‘ ](fg:#FFFFFF bg:#903284)\
#[î‚¼](fg:prev_bg bg:#3B237A)$username\

format = """
$username\
[î‚¶](fg:#F0986F bg:prev_bg)$directory\
([î‚¶](fg:#7AB2D3 bg:prev_bg)$git_branch$git_status)\
[î‚¶](fg:#2C597F bg:prev_bg)$time
[>](fg:#D0D0D0) 
"""

command_timeout = 750

add_newline = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#D65B71"
style_root = "fg:#FFFFFF bg:#D65B71"
format = "[î‚¶](fg:#D65B71)[ï€‡ $user ]($style)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "fg:#000000 bg:#F0986F"
format = "[ï¼ $path ]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸ“¥ "
"Music" = "ó°š "
"Pictures" = "ğŸ“· "

[git_branch]
style = "fg:#000000 bg:#7AB2D3"
format = "[î‚  $branch ]($style)"

[git_status]
style = "fg:#000000 bg:#7AB2D3"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%T ó°ƒ­ CW%V" # Hour:Minute:Second î¼¸ CalendarWeek
style = "fg:#FFFFFF bg:#2C597F"
format = "[ï€— $time [î‚´](#2C597F)]($style)"